version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 25
  reviewers:
  - tdittmann
  assignees:
  - tdittmann
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.1102.0
